---
- name: install vim and zip
  hosts: servers
  remote_user: root
  tasks:

  - name: remove vim, zip and unzip
    apt:
      name:
        - vim
        - zip
        - unzip
      state: absent
  
  - name: update repo
    apt:
      update_cache: yes

